In [3]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import numpy as np
from datos import Datos
from estrategiasparticionado.validacion_cruzada import ValidacionCruzada
from estrategiasparticionado.validacion_simple import ValidacionSimple
from clasificadores.clasificador_naive_bayes import ClasificadorNaiveBayes
dataset=Datos('./conjunto_datos/tic-tac-toe.data')
dataset2=Datos('./conjunto_datos/german.data')
dataset.datos[:,[1, -1]]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


array([[-3., -2.],
       [-3., -2.],
       [-3., -2.],
       ..., 
       [-3., -1.],
       [-3., -1.],
       [-2., -1.]])

In [4]:
validacionSimple = ValidacionSimple()
validacionSimple.creaParticiones(dataset.datos)
for particion in validacionSimple.particiones:
    print(particion.indicesTrain)
    print(particion.indicesTest)

[950 824 366 746 340  93 514 123 167 526 190 150 762 930 357 398 875  20
 603 741 580  46 639 547 771 576  60 288 368 282 834 823 640 884 367  41
 289 819 599 838 507 420 492 240 588 833 311 501 667 422 719 842 663 140
 380 245 814 324   1 751 699 641 326 785 716 139 769 538 920 120 126 266
 406 227 740 850   5  66 121 191 354 215 138 147  44 828 813 949 270 669
 739 579  58 319 558 720 352 519  14 586 405 855 916 313  90 572 684 533
 847 387 513 890 149 508 132 879 595 567 630 765 633 606 303 133 698  37
 445 561 100   2 861 335 646 551 200 458 692   6 774 600 854 708 840  43
 531 830 676 696 455 512 425 632 305 299 441  84 212 661 261 605 934 714
 386 893 435 645 953 635 348 152 327 679 721 414 747 418 293 146 490 650
 358 658  50 924 409 702 846 314 914 278 878  33 231 388 660 260 417 937
  51 652 343 560 570 892 264   8 886 119 761 328 532  47 818 144 624 315
 202 881 825 829 555  72 148  32 565 163 510 331 134 837 936 900 726 101
 129 393 111  27 848  19  35 192 276 778 382 782 56

In [44]:
validacionCruzada = ValidacionCruzada()

validacionCruzada.creaParticiones(dataset.datos)

    
validacionCruzada.particiones[0].indicesTrain

ffff [ 57 834 856  77 908 595 778 546 344 543 716 245 860 793 330 432 646 542
 600  30 705 946 157 591 733 442 662 228  42 886 387  90 659 212 606 385
 313 731 287 483 924 741 701  68 229 709 608 272 202 814 573 437 884  64
  67 873  78 799  34 227 341 355 652 757 685 828 516 794 486 771 500 519
 103 471 132 328 660 798  44 474 480 274 271 376 169 702 331  21 446 135
 697 230 375 678 820 859  87 847  33 411 663 929 258 112 805 852 564 294
 496 616 238  26 252 352 801 155 226 869 760 928 605  48 323 651 948 353
 119  98 596 549 383 680 939 223 126 165 163  37 670 381 345 785  79 882
 184 545 551 276 547 880 491 538 593 870 752 957 712 711 273 552 502 435
 736 816 348 598  60 422 139 579 833 404 781 721  83 107 114 902  14 921
 111 532  23 415 159 854 657 836 470 739  55 495 247 914 830 819 349 498
 171 311 262 424 930 417 193 280 613 337 511 286 217  56 419 522 448 789
 728 954 797 388 513 427  94 611  88 802 359 813 607 557 786  11 750 614
 751 161  89 255 861 329 278  36 455 461 473 3

array([ 57, 834, 856,  77, 908, 595, 778, 546, 344, 543, 716, 245, 860,
       793, 330, 432, 646, 542, 600,  30, 705, 946, 157, 591, 733, 442,
       662, 228,  42, 886, 387,  90, 659, 212, 606, 385, 313, 731, 287,
       483, 924, 741, 701,  68, 229, 709, 608, 272, 202, 814, 573, 437,
       884,  64,  67, 873,  78, 799,  34, 227, 341, 355, 652, 757, 685,
       828, 516, 794, 486, 771, 500, 519, 103, 471, 132, 328, 660, 798,
        44, 474, 480, 274, 271, 376, 169, 702, 331,  21, 446, 135, 697,
       230, 375, 678, 820, 859,  87, 847,  33, 411, 663, 929, 258, 112,
       805, 852, 564, 294, 496, 616, 238,  26, 252, 352, 801, 155, 226,
       869, 760, 928, 605,  48, 323, 651, 948, 353, 119,  98, 596, 549,
       383, 680, 939, 223, 126, 165, 163,  37, 670, 381, 345, 785,  79,
       882, 184, 545, 551, 276, 547, 880, 491, 538, 593, 870, 752, 957,
       712, 711, 273, 552, 502, 435, 736, 816, 348, 598,  60, 422, 139,
       579, 833, 404, 781, 721,  83, 107, 114, 902,  14, 921, 11

In [4]:
dataset.extraeDatosTrain(0)

array([-3., -3., -3., -3., -2., -2., -3., -2., -2., -2.])

In [5]:
clasificador = ClasificadorNaiveBayes()
clasificador.laplace_smoothing = 0.0
res = clasificador.validacion(validacionSimple, dataset)
print(res)
print(clasificador.prioris)
clasificador.errores

[[-2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -1.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -1.0, -2.0, -2.0, -2.0, -1.0, -2.0, -1.0, -1.0, -2.0, -2.0, -1.0, -1.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -1.0, -1.0, -2.0, -2.0, -1.0, -2.0, -1.0, -2.0, -1.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -1.0, -2.0, -1.0, -1.0, -2.0, -1.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -1.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2.0, -1.0, -2.0, -2.0, -1.0, -1.0, -2.0, -2.0, -2.0, -2.0, -1.0, -2.0, -2

[0.29402985074626864]

In [6]:
hist = np.histogram([1, 2, 3,2],bins=len(np.unique([1, 2, 3, 3])))
clasificador.prioris

{-2.0: 0.6462686567164179, -1.0: 0.3537313432835821}

AttributeError: 'ClasificadorNaiveBayes' object has no attribute 'posteriori_args'

In [8]:
matrix = np.array([[1, 0, 1],[1, 0, 0],[1, 0, 1]])
matrix[np.where(matrix[-1] == 1)]

array([[1, 0, 1],
       [1, 0, 1]])

NameError: name 'index' is not defined

In [28]:
import numpy as np
from datos import Datos
from estrategiasparticionado.validacion_cruzada import ValidacionCruzada
from estrategiasparticionado.validacion_simple import ValidacionSimple
from clasificadores.clasificador_naive_bayes import ClasificadorNaiveBayes
dataset=Datos('./conjunto_datos/german.data')
dataset.datos
clasificador = ClasificadorNaiveBayes()
clasificador.laplace_smoothing = 1
res = clasificador.validacion(validacionSimple, dataset)
clasificador.errores

[0.25142857142857145]

In [29]:
clasificador = ClasificadorNaiveBayes()
res = clasificador.validacion(validacionSimple, dataset)
clasificador.errores

[0.24428571428571427]