In [17]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import numpy as np
from datos import Datos
from estrategiasparticionado.validacion_cruzada import ValidacionCruzada
from estrategiasparticionado.validacion_simple import ValidacionSimple

dataset=Datos('./conjunto_datos/tic-tac-toe.data')
dataset2=Datos('./conjunto_datos/german.data')
dataset.datos[:,[1, -1]]

array([[ 2.,  1.],
       [ 2.,  1.],
       [ 2.,  1.],
       ..., 
       [ 2.,  0.],
       [ 2.,  0.],
       [ 1.,  0.]])

In [18]:
validacionSimple = ValidacionSimple()
validacionSimple.creaParticiones(dataset.datos)
for particion in validacionSimple.particiones:
    print(particion.indicesTrain)
    print(particion.indicesTest)

[247 231  16 229 542 818 625   0 244 897 935   6  24 330 675 221 568 335
 350 671 502 587 497 855 256 634 420 807 662 902 437 746 219 379  73 397
 233 517 500 243 951 616 458 611  84 101 794 695  64  57 893 218 488 271
 681  92 324 947 683 749 698 530 718 785 642 748 481 554 747 119 581 339
 942 409 605 806  15 392 166 669 261 477 786 932  62 298 404 264 808 548
 236 622 531 593 349 753 125  49 433 789   4 419 490 922 633 240 494 636
 105 550 563 496 203 601 541 733 112 560 277 351 805 117 740 841 315 237
 648 293 383 578 378   2 910 354 656 321 776 320 596 863 728 848 828 133
  39 468 788 470  17 457 888 100 313 765 627 763 651 674 386  91 272 925
 183 924 857 693 372 638  81  23 562 322 411 706 890  65 195 124 887  54
 181 864 268 111 870 428 444 729 480 711 752 934 896 520 172 260 812  53
 327 609 866 791   7 783 102 204 434 446  66 618 527 571 228 849 291 659
 539  51 159 439  48  79 712  35 700  32 732  82 758 476  26 262  50 337
 140  68 197 207 615 907 230 400 612 577  18 736  6

In [19]:
validacionCruzada = ValidacionCruzada()

validacionCruzada.creaParticiones(dataset.datos)

    
validacionCruzada.particiones[0].indicesTrain

array([288, 913, 627, 675, 310, 788, 173, 482, 763, 604, 395, 176, 955,
       103, 842,  88, 524,  79, 545, 873, 153, 492, 455,  12, 801, 910,
       945, 155, 552, 169, 550,  61,  57, 847,  28, 671, 598, 413, 375,
       307, 802, 722, 325, 699,  90, 612, 270, 174,  60, 644, 625, 877,
       806, 663, 879,  74, 851,  86, 940, 752, 835, 217, 768, 850,   1,
       167, 823,   4, 458,  98, 320, 751, 553,  23, 687, 609, 866, 755,
       302, 754, 899,  11, 269, 781, 403, 124, 127, 436, 611, 833, 949,
       512, 703, 326, 483, 859, 670, 573, 789, 856, 255, 453, 210, 716,
        69, 312, 494, 633, 926, 884, 518, 347, 807, 457, 613, 474, 264,
       184, 720, 193, 189, 451, 503, 719, 902, 134,  44, 756, 149, 290,
       463, 591, 709, 301, 819, 432,  37, 142, 894, 387, 394, 386, 725,
       646,  76, 374, 704, 593, 368, 588, 377, 502, 918, 924, 743, 844,
       626, 381, 590, 287, 473, 629, 274, 219, 102, 795, 254,  30, 664,
       475, 824, 616, 333,  22, 653, 204,  38, 941, 705, 191, 14

In [20]:
dataset.extraeDatosTrain(0)

array([ 2.,  2.,  2.,  2.,  1.,  1.,  2.,  1.,  1.,  1.])

In [29]:
import numpy as np
from datos import Datos
from estrategiasparticionado.validacion_cruzada import ValidacionCruzada
from estrategiasparticionado.validacion_simple import ValidacionSimple
from clasificadores.clasificador_vecinos_proximos import ClasificadorVecinosProximos

dataset=Datos('./conjunto_datos/german.data')
dataset.datos
clasificador = ClasificadorVecinosProximos()


res = clasificador.validacion(validacionSimple, dataset)
clasificador.errores

5


IndexError: invalid index to scalar variable.

In [29]:
clasificador = ClasificadorNaiveBayes()
res = clasificador.validacion(validacionSimple, dataset)
clasificador.errores

[0.24428571428571427]

In [14]:
import numpy.linalg as LA


LA.norm([1,1],ord=3)

1.2599210498948732