In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import numpy as np
from datos import Datos
from estrategiasparticionado.validacion_cruzada import ValidacionCruzada
from estrategiasparticionado.validacion_simple import ValidacionSimple
from clasificadores.clasificador_regresion_logistica import ClasificadorRegresionLogistica

dataset=Datos('./conjunto_datos/tic-tac-toe.data')
dataset2=Datos('./conjunto_datos/german.data')
dataset.datos[:,[1, -1]]

array([[ 2.,  1.],
       [ 2.,  1.],
       [ 2.,  1.],
       ..., 
       [ 2.,  0.],
       [ 2.,  0.],
       [ 1.,  0.]])

In [2]:
validacionSimple = ValidacionSimple()
validacionSimple.creaParticiones(dataset.datos)
for particion in validacionSimple.particiones:
    print(particion.indicesTrain)
    print(particion.indicesTest)

[160 793 164 407 576 528 533 729 743 266 139 222 210 168 480 607 860 184
  98 940 687 415 644 536 197 220 581 598 741 232 511 610 601 482 308 557
 358 373 926 290 946 947 101 493 643   8 127 224 490  57 417 441 428 622
 297 611 488 586 479 506 705 750  67 951 234 484 762 522 540 749 792 142
 572 596  84 271 303 386 250 474 270 362 174 870 852 466 219 825 273 578
 872 269 173  59 113 406 316 939 381 910 150 890 130  19 354 537 803 887
  54 446 626 247 854 788  87 915 399 943 595 831 145 695 470 696 547 363
 670 571 242 606 846 843 367  62 667 787 864 862 328 228 662 721 632 293
 318 615 126 380 332 252  20 764  51 162 646 855 514 842 409 396 885 256
 888  94 509 613 356 945 410 661 258 579 801 853 710 932 421 461 398   3
  75 840 212 790 920  39  31 353 238 655  82  43 746  16 566 330 573 678
 765 737 914 554 806 758  63 556 405  79 154  21 239  77 954 612 577 923
   4 382 756 350 829 481 889 836 371 458 805 942 519 543  18  92 633  81
 117 804 345 209 798  11 169 422 134 340 352 724 81

In [3]:
validacionCruzada = ValidacionCruzada()

validacionCruzada.creaParticiones(dataset.datos)

    
validacionCruzada.particiones[0].indicesTrain

array([675,  63, 793, 784, 479, 421, 805, 697, 589, 489, 236, 401, 679,
        92, 726,  21, 671, 916, 633, 676, 621, 611, 268, 148,  29, 398,
       847, 496, 334,  27, 745, 630, 513, 230, 946, 315, 337, 739, 463,
       218, 439, 436, 183, 771, 772,   7, 209, 617, 759,  98, 600, 535,
       330, 750, 880, 729, 667, 448, 547, 728, 647, 866, 906, 267, 879,
       457, 944, 546, 114, 766, 615, 458, 287, 161, 144, 181, 720, 215,
       187, 949, 932, 178,  47, 523, 923, 818, 785,  57, 735, 185, 929,
       953, 593, 111, 791, 443, 814, 672, 690, 563, 353, 905, 886, 235,
        36, 635, 255,  72, 332, 397, 557, 740, 309, 639, 290, 532, 687,
        35, 302,  44, 915, 262,  60, 478, 518, 388, 500, 134, 298, 582,
       297, 590, 263, 749, 554, 734, 455, 762, 670, 460, 503, 855,  13,
       336,  46, 763,  23, 912, 429, 891, 789, 701, 414, 412,  88, 601,
       832, 662, 157, 760, 603, 952, 419, 862, 924, 779, 664, 495, 394,
       951, 411, 790,   0,  80, 591, 207, 350, 122, 831, 437, 65

In [4]:
dataset.extraeDatosTrain(0)

array([ 2.,  2.,  2.,  2.,  1.,  1.,  2.,  1.,  1.,  1.])

In [21]:
clasificador = ClasificadorRegresionLogistica()
res = clasificador.validacion(validacionSimple, dataset)
print(res)


[ 0.91006909  0.72175543  0.96506334  0.61912121  0.88607877  0.96546911
  0.99137923  0.99052073  0.89897617  0.92890383  0.97119399  0.95761212
  0.55731218  0.73797783  0.79324704  0.79084656  0.87845303  0.83176245
  0.97379857  0.96663746  0.96622673  0.87204193  0.99285291  0.95330974
  0.74952615  0.89887716  0.961953    0.95976109  0.99232312  0.95312598
  0.90394738  0.95808528  0.98309132  0.94581688  0.67888984  0.80705688
  0.71487928  0.9361124   0.9461812   0.98572635  0.89723833  0.73348426
  0.93020433  0.95127447  0.34293448  0.97687942  0.95387174  0.97286795
  0.95497527  0.92603674  0.32725192  0.92422138  0.94455461  0.97775275
  0.82986607  0.42005174  0.8142571   0.7981274   0.99108558  0.64582206
  0.93093464  0.98027645  0.94735453  0.90749866  0.92220613  0.93227497
  0.62195385  0.85855475  0.88908573  0.91734572  0.93552414  0.85302583
  0.98723611  0.72870543  0.93125223  0.95701467  0.86256508  0.36168835
  0.92837647  0.94253167  0.92812107  0.86452883  0

In [17]:
hist = np.histogram([1, 2, 3,2],bins=len(np.unique([1, 2, 3, 3])))
clasificador.prioris

AttributeError: 'ClasificadorRegresionLogistica' object has no attribute 'prioris'

In [ ]:
matrix = np.array([[1, 0, 1],[1, 0, 0],[1, 0, 1]])
matrix[np.where(matrix[-1] == 1)]

In [51]:
import numpy as np
from datos import Datos
from estrategiasparticionado.validacion_cruzada import ValidacionCruzada
from estrategiasparticionado.validacion_simple import ValidacionSimple
from clasificadores.clasificador_regresion_logistica import ClasificadorRegresionLogistica
dataset=Datos('./conjunto_datos/example1.data')
dataset.datos
clasificador = ClasificadorRegresionLogistica()
res = clasificador.validacion(validacionSimple, dataset)
clasificador.errores

[ 0.582053    0.58691997  0.57201855  0.65323734  0.5952221   0.60421096
  0.58547062  0.57845826  0.58277962  0.58988392  0.61298794  0.50099575
  0.50727777  0.59173041  0.5828016   0.51925329  0.56064099  0.59928528
  0.52075064  0.59705111  0.59508037  0.58431463  0.59385788  0.63220335
  0.52531919  0.59728629  0.59706787  0.59925416  0.42420876  0.58249587
  0.59095299  0.50106006  0.63187426  0.57260018  0.59885399  0.51606728
  0.563687    0.53004342  0.58092626  0.61403061  0.58238227  0.53994917
  0.59658705  0.60761792  0.45244247  0.61815725  0.5317438   0.49393101
  0.59952724  0.61251686  0.59928079  0.60150148  0.57654377  0.61575757
  0.57427792  0.60040642  0.59812699  0.57466187  0.58010148  0.59791747
  0.58742047  0.59994167  0.56350619  0.58496388  0.5818939   0.61140975
  0.58022898  0.64550378  0.58626172  0.53612071  0.56804815  0.59555697
  0.55645809  0.59214347  0.59049789  0.61538961  0.62179512  0.57362617
  0.59007999  0.59071295  0.61493463  0.58963027  0

[0.4714285714285714]

In [ ]:
clasificador = ClasificadorNaiveBayes()
res = clasificador.validacion(validacionSimple, dataset)
clasificador.errores

In [80]:
from plotModel import plotModel
import matplotlib.pyplot as plt
%matplotlib inline


dataset=Datos('./conjunto_datos/example4.data')
dataset.datos
clasificador = ClasificadorRegresionLogistica()
res = clasificador.validacion(validacionSimple, dataset)

estrategia = ValidacionSimple()
estrategia.creaParticiones(dataset.datos)
ii = estrategia.particiones[-1].indicesTrain
plotModel(dataset.datos[ii,0],dataset.datos[ii,1],dataset.datos
[ii,-1]!=0,clasificador,"Frontera",dataset.diccionarios)
clasificador.errores



/Users/dani/Documents/FAA/clasificadores/clasificador_regresion_logistica.py:39: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-prod_escalar))


ValueError: operands could not be broadcast together with shapes (3,) (31,) 